packages:
  - .

nodeLinker: hoisted
autoInstallPeers: false
allowBuilds:
  '@google/genai': false
  node-pty: true
  protobufjs: false
minimumReleaseAgeExclude:
  - '@deepseek-ai/dsh-typert-protocol@0.1.0-rc.6'
  - '@deepseek-ai/dsh-invariants@0.1.0-rc.6'
  - dsh-better-sidebar@0.17.1
overrides:
  '@deepseek-harness/dsh-mathmodel': link:../../../plugins/dsh-mathmodel
patchedDependencies:
  dsh-plugin-subscriptions@0.5.2: patches/dsh-plugin-subscriptions@0.5.2.patch
